### ISSUE TITLE
Conflict intermediate table name when multiple embulk runs at once.

### ISSUE THREAD

**Issue by hiroyuki-sato** [embulk/embulk-output-jdbc#205] opened 2017-10-04 10:47 UTC
A user runs multiple Embulk commands at once. 
It reads input data from MySQL cluster (A-DB, B-DB) and loads it into the same tales in redshift DB.
In this case, when multiple embulk uses same intermediate table name, the load will fail.

If a temporary table has a unique name, this issue may solve. 

Ref: [Twitter](https://twitter.com/hiruandon2nd/status/915468504752467968) written in Japanese.

**Comment by hiruandon** [comment] 2017-10-04 11:30
Thank you for creating Issue.

The error message when conflict occurs is as follows.
`ERROR: duplicate key violates unique constraint "pg_class_relname_nsp_index" (possibly caused by concurrent transaction conflict)`
(It seems to be postgresql, but the DB where the error occurred is AWS-Redshift.)

Error detail(gist):[Jenkins Error Log](https://gist.github.com/hiruandon/e587b6b34f614995ceb1c54cc008ff51)

**Comment by hito4t** [comment] 2017-10-05 02:33
@hiruandon 
Hi,
Can you show version of embulk-output-redshift plugin?

**Comment by hiruandon** [comment] 2017-10-05 05:13
Sorry,additional information.

- Jenkins v1.596.2
-- Run Embulk's job in parallel against the clustered MySQL-DB.
- MySQL v5.5.56(Input)
- Amazon Redshift(Output)
- Embulk v0.7.10
- embulk-input-mysql (0.6.1)
- embulk-output-redshift (0.4.3)

It is a log when duplication occurs.
(DB cluster names are "CL01" and "CL02".)
Temporary table name "login_month_329ab640_bl_tmp000" is duplicated.

1. [CL02-Log](https://gist.github.com/hiruandon/5b186e9b4462e7bfb195ace4411ad448)
2. [CL01-Log](https://gist.github.com/hiruandon/bdd958b9e5f723743c49c1c80038053d)

**Comment by hito4t** [comment] 2017-10-05 05:46
@hiruandon 
#172 may solve the issue.
It was already released.
Would you try again with latest embulk-output-redshift ?

**Comment by hiruandon** [comment] 2017-10-05 06:39
@hito4t

Thank you for the information.
Check if the latest version is executable on the test server.
Please give me some time.

**Comment by hiruandon** [comment] 2017-11-08 02:34
Since the environment for testing can be prepared,
I installed the latest version of embulk-output-redshift(0.7.11).
And, for a few days, I will see the state.

**Comment by hiruandon** [comment] 2017-11-29 06:25
@hito4t

An error occurred.

`org.embulk.exec.PartialExecutionException: java.lang.RuntimeException: org.embulk.spi.util.RetryExecutor$RetryGiveupException: org.postgresql.util.PSQLException: ERROR: Relation "usersecretl_19ed92c0_bl_tmp000" already exists`

Server information.

- Jenkins v1.596.2
-- Run Embulk's job in parallel against the 10 clustered Azure SQL Database(12.0.2000.8).
- Embulk v0.8.36
-- embulk-input-sqlserver (0.8.5)
-- embulk-output-redshift (0.7.11)
- Amazon Redshift(Output)

Target Tables.

1. UserSecretLessonHistories
1. UserSecretLessons

Conflict Table Name.

- usersecretl_19ed92c0_bl_tmp000

Logs.

1. [【Log】UserSecretLessonHistories](https://gist.github.com/hiruandon/adc33c6123c6c115f4bd57cf85fcca9e)
1. [【Log】UserSecretLessons](https://gist.github.com/hiruandon/9a7c1d5dff1b339123b458305888155b)

Question.

1. What is the behavior of the latest version if the table already exists?
-- If temporary table names conflict, will you generate another table name and retry?

**Comment by hito4t** [comment] 2017-11-29 07:09
@hiruandon 
> If temporary table names conflict, will you generate another table name and retry?

No, embulk-output-jdbc will generate same table name...
It will work if existing temporary table is dropped between retrying, but otherwise will fail.

I'll correct as soon as possible.

**Comment by hito4t** [comment] 2017-11-29 07:25
I've created the PR #217 .

**Comment by hito4t** [comment] 2017-11-29 07:59
@hiruandon 
embulk-output-redshift defines max length for table name is 30 (why?), but actually it is 127 bytes.
http://docs.aws.amazon.com/redshift/latest/dg/r_CREATE_TABLE_NEW.html
I'll correct.

**Comment by hiruandon** [comment] 2017-11-29 09:12
@hito4t 

30?Oh.. It is a mystery...

**Comment by hito4t** [comment] 2017-11-29 11:49
@hiruandon 
Perhaps it was copied from embulk-output-oracle.

**Comment by hito4t** [comment] 2017-11-30 01:44
I've corrected.
https://github.com/embulk/embulk-output-jdbc/pull/217/commits/7dac89ce3db554fd45b86551f350be82316bcf9f

**Comment by hito4t** [comment] 2017-12-08 08:02
@hiruandon 
I've merged the PR and released the new version!

**Comment by hiruandon** [comment] 2018-01-15 01:26
@hito4t 
@hiroyuki-sato 
I'm using a new version.
I watched the situation for one month, but there is no error.
Thank you for the release!

**Closed** 2018-01-15 02:13 UTC
